install.packages(c("dplyr", "tidyr", "data.table", "ggplot2", "plotly", "esquisse", "caret", "tidymodels", "randomForest", "xgboost", "lubridate"))
library(dplyr)
library(tidyr)
library(data.table)
library(ggplot2)
library(plotly)
library(esquisse)
library(caret)
library(tidymodels)
library(randomForest)
library(xgboost)
library(lubridate)

athlete_biography <- fread("data/Olympic_Athlete_Biography.csv")
athlete_events <- fread("data/Olympic_Athlete_Event_Details.csv")
country_profile <- fread("data/Olympic_Country_Profile.csv")
event_results <- fread("data/Olympic_Event_Results.csv")
games_summaru <- fread("data/Olympic_Games_Summary.csv")
medal_tally <- fread("data/Olympic_Medal_Tally.csv")